import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Beer collection',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="top-0 h-14 border-b fixed w-full flex items-center bg-black z-10">
          <div className="px-4 w-full lg:px-0 lg:container lg:mx-auto flex justify-between">
            <Link href="/">Beer collection</Link>
            <Link href="/add-beer">Add beer</Link>
          </div>
        </header>
        <div className="container mx-auto mt-28">{children}</div>
      </body>
    </html>
  );
}
